version: "3.9"

services:
  postgres-auth:
    image: postgres:16
    container_name: authgate_postgres_auth
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: locaguest
      POSTGRES_DB: AuthGate
    ports:
      - "5432:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data

  postgres-audit:
    image: postgres:16
    container_name: authgate_postgres_audit
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: locaguest
      POSTGRES_DB: AuthGateAudit
    ports:
      - "5433:5432"
    volumes:
      - pgdata-audit:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: authgate_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  # Optional structured logs server (Seq)
  seq:
    image: datalust/seq:2023-lts
    container_name: authgate_seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  authgate-api:
    build:
      context: .
      dockerfile: src/AuthGate.Auth/Dockerfile
    container_name: authgate_api
    restart: unless-stopped
    depends_on:
      - postgres-auth
      - postgres-audit
      - mailhog
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Jwt__Secret: YourSuperSecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm!
      Jwt__Issuer: AuthGate
      Jwt__Audience: AuthGate
      ConnectionStrings__DefaultConnection: Host=postgres-auth;Port=5432;Database=AuthGate;Username=postgres;Password=locaguest
      ConnectionStrings__AuditConnection: Host=postgres-audit;Port=5432;Database=AuthGateAudit;Username=postgres;Password=locaguest
      Cors__AllowedOrigins__0: http://localhost:4200
      Email__SmtpHost: mailhog
      Email__SmtpPort: "1025"
      Email__FromAddress: noreply@authgate.com
      Email__FromName: AuthGate
      Seq__ServerUrl: http://seq
    ports:
      - "8080:8080"
      - "8081:8081"
    # Healthcheck simple hitting the swagger or root
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

volumes:
  pgdata-auth:
  pgdata-audit:

